name: Test CPP Project

on:
  workflow_call:
    inputs:
        team-name:
            required: true
            type: string
        pr_head_sha:
            required: true
            type: string
        machine_name:
            required: true
            type: string
    secrets:
        test-repo:
            required: true
        auth-token:
            required: true
        backend-url:
            required: true
        auth-key:
            required: true

jobs:
  test-bug-101:
    name: Run test for BUG-101
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 101
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG101 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-101"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-102:
    name: Run test for BUG-102
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 102
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG102 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-102"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-103:
    name: Run test for BUG-103
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 103
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG103 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-103"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-104:
    name: Run test for BUG-104
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 104
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG104 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-104"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-105:
    name: Run test for BUG-105
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 105
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG105 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-105"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-106:
    name: Run test for BUG-106
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 106
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG106 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-106"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-107:
    name: Run test for BUG-107
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 107
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG107 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-107"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-108:
    name: Run test for BUG-108
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 108
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG108 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-108"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-110:
    name: Run test for BUG-110
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 110
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG110 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-110"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-111:
    name: Run test for BUG-111
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 111
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG111 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-111"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-112:
    name: Run test for BUG-112
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 112
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG112 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-112"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-113:
    name: Run test for BUG-113
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 113
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG113 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-113"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-114:
    name: Run test for BUG-114
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 114
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG114 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-114"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-115:
    name: Run test for BUG-115
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 115
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG115 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-115"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-116:
    name: Run test for BUG-116
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 116
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG116 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-116"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-117:
    name: Run test for BUG-117
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 117
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG117 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-117"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-118:
    name: Run test for BUG-118
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 118
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG118 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-118"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-119:
    name: Run test for BUG-119
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 119
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG119 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-119"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-120:
    name: Run test for BUG-120
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 120
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG120 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-120"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-121:
    name: Run test for BUG-121
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 121
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG121 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-121"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-122:
    name: Run test for BUG-122
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 122
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG122 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-122"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-123:
    name: Run test for BUG-123
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 123
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG123 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-123"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-124:
    name: Run test for BUG-124
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 124
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG124 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-124"}'; fi
          exit ${result}
        continue-on-error: true

  test-bug-125:
    name: Run test for BUG-125
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 125
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG125 > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-125"}'; fi
          exit ${result}
        continue-on-error: true