name: Test CPP Project

on:
  workflow_call:
    inputs:
        team-name:
            required: true
            type: string
        pr_head_sha:
            required: true
            type: string
        machine_name:
            required: true
            type: string
    secrets:
        test-repo:
            required: true
        auth-token:
            required: true
        backend-url:
            required: true
        auth-key:
            required: true

jobs:
  test-bug-01:
    name: test-bug-01
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 101 and report status # Updated name
        shell: bash {0}
        run: |
          set +e # Allow script to continue after test failure
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG101 > test_output.log 2>&1 # Run test
          result=$? # Capture exit code
          test_status="" # Initialize status variable
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail" # Set status to fail
          else
              echo "Test PASSED"
              test_status="pass" # Set status to pass
          fi
          echo "Sending status '$test_status' to backend..."
          # Send curl request regardless of result, include the status
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-101\",
                \"status\": \"$test_status\"
            }"
          # Exit with the original test result code
          exit ${result}

  test-bug-02:
    name: test-bug-02
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 102 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG102 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-102\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-03:
    name: test-bug-03
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 103 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG103 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-103\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-04:
    name: test-bug-04
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 104 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG104 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-104\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-05:
    name: test-bug-05
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 105 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG105 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-105\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-06:
    name: test-bug-06
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 106 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG106 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-106\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-07:
    name: test-bug-07
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 107 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG107 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-107\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-08:
    name: test-bug-08
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 108 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParallelizationTest.BUG108 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-108\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-09:
    name: test-bug-09
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 110 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG110 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-110\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-10:
    name: test-bug-10
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 111 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG111 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-111\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-11:
    name: test-bug-11
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 112 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG112 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-112\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-12:
    name: test-bug-12
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 113 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ContainmentFieldTest.BUG113 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-113\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-13:
    name: test-bug-13
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 114 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG114 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-114\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-14:
    name: test-bug-14
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 115 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG115 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-115\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-15:
    name: test-bug-15
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 116 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG116 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-116\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-16:
    name: test-bug-16
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 117 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG117 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-117\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-17:
    name: test-bug-17
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 118 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG118 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-118\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-18:
    name: test-bug-18
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 119 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=ParticleTest.BUG119 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-119\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-19:
    name: test-bug-19
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 120 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG120 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-120\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-20:
    name: test-bug-20
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 121 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG121 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-121\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-21:
    name: test-bug-21
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 122 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG122 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-122\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-22:
    name: test-bug-22
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 123 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG123 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-123\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-23:
    name: test-bug-23
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 124 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG124 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-124\",
                \"status\": \"$test_status\"
            }"
          exit ${result}

  test-bug-24:
    name: test-bug-24
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}
      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: cpp
          sparse-checkout-cone-mode: false
          path: tests
      - name: Update CMakeLists
        run: |
            mv tests/cpp/* tests/
            rm -f CMakeLists.txt
            mv tests/CMakeLists.txt ./
            rm -rf tests/cpp
      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential cmake git
      - name: Install GCC (C++17 support)
        run: |
            sudo apt install -y g++-10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
            g++ --version
      - name: Verify CMake Version
        run: |
            cmake --version
            cmake_min_version=$(cmake --version | head -n1 | awk '{print $3}')
            required_version="3.10"
            if [ "$(printf '%s\n' "$required_version" "$cmake_min_version" | sort -V | head -n1)" != "$required_version" ]; then
                echo "CMake version is lower than 3.10"
                exit 1
            fi
      - name: Build Project
        run: |
            mkdir -p build && cd build
            cmake ..
            make
      - name: run test on bug 125 and report status # Updated name
        shell: bash {0}
        run: |
          set +e
          build/quantum_tests --gtest_filter=SimulationTest.BUG125 > test_output.log 2>&1
          result=$?
          test_status=""
          if [ ${result} -ne 0 ]; then
              echo "Test FAILED"
              test_status="fail"
          else
              echo "Test PASSED"
              test_status="pass"
          fi
          echo "Sending status '$test_status' to backend..."
          curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d "{
                \"teamName\": \"${{ inputs.team-name }}\",
                \"bugCode\": \"BUG-125\",
                \"status\": \"$test_status\"
            }"
          exit ${result}