name: Auto Marking

on:
  workflow_call:
    inputs:
        team-name:
            required: true
            type: string
        pr_head_sha:
            required: true
            type: string
        machine_name:
            required: true
            type: string
    secrets:
        test-repo:
            required: true
        auth-token:
            required: true
        backend-url:
            required: true
        auth-key:
            required: true
        firebase-token:
            required: true

# NOTE: The bug codes (e.g., BUG-102, BUG-GREYSCALE) are placeholders.
# Replace them with the actual codes used by your backend system if they differ.

jobs:
  test-bug-01:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Make API Call
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/resize \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png", "width": 800, "height": 600}' || exit 1

      - name: Run Test 01
        run: |
            python test/single_tests/test_resized_image.py  > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-201"}'; fi
            exit ${result}


  test-bug-02:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Greyscale API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/greyscale \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 02
        run: |
            python test/single_tests/test_greyscale_image.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-202"}'; fi
            exit ${result}

  test-bug-03:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Negative API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/negative \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 03
        run: |
            python test/single_tests/test_negative_image.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-203"}'; fi
            exit ${result}

  test-bug-04:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Contrast API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/contrast \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png", "contrast": 20}' || exit 1

      - name: Run Test 04
        run: |
            python test/single_tests/test_contrast_20.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-204"}'; fi
            exit ${result}

  test-bug-05:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Rotate API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/rotate \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png", "angle": 90}' || exit 1

      - name: Run Test 05
        run: |
            python test/single_tests/test_rotated_image.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-205"}'; fi
            exit ${result}

  test-bug-06:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Sharpen API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/sharpen \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 06
        run: |
            python test/single_tests/test_sharpened_image.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-206"}'; fi
            exit ${result}

  test-bug-07:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Emboss API
        run: |
          npx concurrently "npm run start" "npm run start:basic-processing" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000, 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/emboss \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 07
        run: |
            python test/single_tests/test_embossed_standard.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-207"}'; fi
            exit ${result}

  test-bug-08:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Histogram Equalization API
        run: |
          npx concurrently "npm run start" "npm run start:enhancement" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4002 && break
            echo "Waiting for ports 3000, 4002..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/enhancement/histogram-equalization \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 08
        run: |
            python test/single_tests/test_histogram_equalized.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-208"}'; fi
            exit ${result}

  test-bug-09:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Flood Fill API
        run: |
          npx concurrently "npm run start" "npm run start:enhancement" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            # Fixed nc command syntax
            nc -z localhost 3000 && nc -z localhost 4002 && break
            echo "Waiting for ports 3000, 4002..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/enhancement/flood_fill_image \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png", "sr": 400, "sc": 250, "newColor": "[255, 0, 0]"}' || exit 1

      - name: Run Test 09
        run: |
            python test/single_tests/test_flood_filled_input.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-209"}'; fi
            exit ${result}

  test-bug-10:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Canny Edge Detection API
        run: |
          npx concurrently "npm run start" "npm run start:feature-detection" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4003 && break
            echo "Waiting for ports 3000, 4003..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/feature-detection/canny-edge-detection \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

      - name: Run Test 10
        run: |
            python test/single_tests/test_canny_edge_detection.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-210"}'; fi
            exit ${result}

  test-bug-11:
    runs-on: ${{ inputs.machine_name }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: node
          sparse-checkout-cone-mode: false
          path: test

      - name: Setup test files
        run: |
            mv test/node/* test/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Download input image
        run: |
          mkdir -p apps/cse40/images # Ensure directory exists
          wget -O apps/cse40/images/input_image.png "https://firebasestorage.googleapis.com/v0/b/profile-image-1c78a.appspot.com/o/codejam%2Finput_image.png?alt=media&token=${{ secrets.firebase-token }}"

      - name: Start Services and Run Harris Corner Detection API
        run: |
          npx concurrently "npm run start" "npm run start:feature-detection" &
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4003 && break
            echo "Waiting for ports 3000, 4003..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/feature-detection/harris-corner-detection \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png", "k": 0.04, "windowSize": "3", "thresh": 0.00001}' || exit 1

      - name: Run Test 11
        run: |
            python test/single_tests/test_harris_corners.py > /dev/null 2>&1
            result=$?
            if [ ${result} -ne 0 ]; then echo "FAILED"; else echo "PASSED"; curl -X POST ${{ secrets.backend-url }} -H "Content-Type: application/json" -H "x-webhook-token: ${{ secrets.auth-key }}" -d '{"teamName": "${{ inputs.team-name }}","bugCode": "BUG-211"}'; fi
            exit ${result}